In [1]:
import pandas

In [2]:
import numpy

In [3]:
train_path = "Genre Classification Dataset/train_data.txt"
train_data = pandas.read_csv(train_path, sep=':::', names=['Title', 'Genre', 'Description'], engine='python')
train_data

test_path = "Genre Classification Dataset/test_data.txt"
test_data = pandas.read_csv(test_path, sep=':::', names=['Id', 'Title', 'Description'], engine='python')
test_data

,Id,Title,Description
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),Before he was known internationally as a mart...
...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)","Covering multiple genres, Tales of Light & Da..."
54196,54197,Der letzte Mohikaner (1965),As Alice and Cora Munro attempt to find their...
54197,54198,Oliver Twink (2007),A movie 169 years in the making. Oliver Twist...
54198,54199,Slipstream (1973),"Popular, but mysterious rock D.J Mike Mallard..."
54199,54200,Curitiba Zero Grau (2010),"Curitiba is a city in movement, with rhythms ..."

In [4]:
print(train_data)

                                              Title          Genre  \
1                     Oscar et la dame rose (2009)          drama
2                                     Cupid (1997)       thriller
3                 Young, Wild and Wonderful (1980)          adult
4                            The Secret Sin (1915)          drama
5                           The Unrecovered (2007)          drama
...                                             ...            ...
54210                              "Bonino" (1953)         comedy
54211                  Dead Girls Don't Cry (????)         horror
54212    Ronald Goedemondt: Ze bestaan echt (2008)    documentary
54213                     Make Your Own Bed (1944)         comedy
54214   Nature's Fury: Storm of the Century (2006)        history

                                             Description
1       Listening in to a conversation between his do...
2       A brother and sister with a past incestuous r...
3       As the bus empties the students for their fie...
4       To help their unemployed father make ends mee...
5       The film's title refers not only to the un-re...
...                                                  ...
54210   This short-lived NBC live sitcom centered on ...
54211   The NEXT Generation of EXPLOITATION. The sist...
54212   Ze bestaan echt, is a stand-up comedy about g...
54213   Walter and Vivian live in the country and hav...
54214   On Labor Day Weekend, 1935, the most intense ...

[54214 rows x 3 columns]

In [5]:
test_solution_path = "Genre Classification Dataset/test_data_solution.txt"
test_solution_data = pandas.read_csv(test_solution_path, sep=':::', names=['Id', 'Title','Genre', 'Description'], engine='python')
test_solution_data

,Id,Title,Genre,Description
0,1,Edgar's Lunch (1998),thriller,"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),comedy,"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),documentary,One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),drama,"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),drama,Before he was known internationally as a mart...
...,...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)",horror,"Covering multiple genres, Tales of Light & Da..."
54196,54197,Der letzte Mohikaner (1965),western,As Alice and Cora Munro attempt to find their...
54197,54198,Oliver Twink (2007),adult,A movie 169 years in the making. Oliver Twist...
54198,54199,Slipstream (1973),drama,"Popular, but mysterious rock D.J Mike Mallard..."
54199,54200,Curitiba Zero Grau (2010),drama,"Curitiba is a city in movement, with rhythms ..."

In [6]:
print(train_data)

                                              Title          Genre  \
1                     Oscar et la dame rose (2009)          drama
2                                     Cupid (1997)       thriller
3                 Young, Wild and Wonderful (1980)          adult
4                            The Secret Sin (1915)          drama
5                           The Unrecovered (2007)          drama
...                                             ...            ...
54210                              "Bonino" (1953)         comedy
54211                  Dead Girls Don't Cry (????)         horror
54212    Ronald Goedemondt: Ze bestaan echt (2008)    documentary
54213                     Make Your Own Bed (1944)         comedy
54214   Nature's Fury: Storm of the Century (2006)        history

                                             Description
1       Listening in to a conversation between his do...
2       A brother and sister with a past incestuous r...
3       As the bus empties the students for their fie...
4       To help their unemployed father make ends mee...
5       The film's title refers not only to the un-re...
...                                                  ...
54210   This short-lived NBC live sitcom centered on ...
54211   The NEXT Generation of EXPLOITATION. The sist...
54212   Ze bestaan echt, is a stand-up comedy about g...
54213   Walter and Vivian live in the country and hav...
54214   On Labor Day Weekend, 1935, the most intense ...

[54214 rows x 3 columns]

In [7]:
!Pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.12.0)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.0-cp312-cp312-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   - -------------------------------------- 0.4/10.9 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/10.9 MB 2.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.5/10.9 MB 2.8 MB/s eta 0:00:04
   ------- -------------------------------- 2.2/10.9 MB 3.0 MB/s eta 0:00:03
   ---------- ----------------------------- 3.0/10.9 MB 3.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.6/10.9 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 4.4/10.9 MB 3.1 MB/s eta 0:00:03
   ----------------- ---------------------- 4.9/10.9 MB 3.0 MB/s eta 0:00:02
   ---------------------- ----------------- 6.1/10.9 MB 2.9 MB/s eta 0:00:02
   -------------------------- ------------- 7.1/10.9 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/10.9 MB 3.1 MB/s eta 0:00:01
   ----------------------------- ---------- 8.2/10.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/10.9 MB 3.1 MB/s eta 0:00:01
   ------------------------------------ --- 9.9/10.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  10.9/10.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  10.9/10.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 2.8 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/301.8 kB ? eta -:--:--
   ---------------------------------------- 301.8/301.8 kB 6.2 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.0 threadpoolctl-3.5.0

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Load your train and test data
# Assuming `train_data` and `test_solution_data` are pandas DataFrames

# Split the features and labels
X_train = train_data['Description']
y_train = train_data['Genre']
X_test = test_solution_data['Description']
y_test = test_solution_data['Genre']

# Step 1: Tokenization and TF-IDF Vectorization
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Step 2: Label Encoding
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Step 3: Feature Selection
selector = SelectKBest(chi2, k=20000)
X_train_selected = selector.fit_transform(X_train_tfidf, y_train_encoded)
X_test_selected = selector.transform(X_test_tfidf)

# Step 4: Scaling
scaler = StandardScaler(with_mean=False)  # TF-IDF does not support mean centering
X_train_scaled = scaler.fit_transform(X_train_selected)
X_test_scaled = scaler.transform(X_test_selected)

# Step 5: Logistic Regression with Hyperparameter Tuning
log_reg = LogisticRegression()

param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'dual': [False],
    'tol': [0.0001, 0.001, 0.01],
    'C': [0.1, 1, 10],
    'fit_intercept': [True, False],
    'intercept_scaling': [1],
    'class_weight': [None, 'balanced'],
    'random_state': [42],
    'solver': ['lbfgs', 'saga'],
    'max_iter': [100, 200],
    'multi_class': ['ovr', 'multinomial'],
    'verbose': [0],
    'warm_start': [False],
    'n_jobs': [-1],
    'l1_ratio': [None]
}

grid_search = GridSearchCV(log_reg, param_grid, cv=5, verbose=1, n_jobs=-1)
grid_search.fit(X_train_scaled, y_train_encoded)

# Get the best model
best_model = grid_search.best_estimator_

# Step 6: Apply model on scaled train and test data
y_train_pred = best_model.predict(X_train_scaled)
y_test_pred = best_model.predict(X_test_scaled)

# Step 7: Calculate accuracy, precision, recall, and confusion matrix
accuracy = accuracy_score(y_test_encoded, y_test_pred)
precision = precision_score(y_test_encoded, y_test_pred, average='weighted')
recall = recall_score(y_test_encoded, y_test_pred, average='weighted')
conf_matrix = confusion_matrix(y_test_encoded, y_test_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print('Confusion Matrix:')
print(conf_matrix)

Fitting 5 folds for each of 1152 candidates, totalling 5760 fits